Wait till button is >= 90% visible.
Attempting to wait until espresso sees at least 90 % of the play button.

Idea is suggested in https://medium.com/@grajalesblancojorge/android-espresso-test-fake-friends-display-and-click-effective-visibility-e9bc081b3ad4

For the rationale, see the stack trace of the failing test:

```
androidx.test.espresso.PerformException: Error performing 'single click' on view 'with id: org.catrobat.catroid:id/button_play'.
[...]
at org.catrobat.catroid.uiespresso.content.brick.stage.OpenUrlBrickTest.testOpenUrlIntent(OpenUrlBrickTest.java:94)
[...]
Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
at least 90 percent of the view's area is displayed to the user.
Target view: "FloatingActionButton{id=2131362497, res-name=button_play, visibility=VISIBLE, width=112, height=112, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=android.widget.RelativeLayout$LayoutParams@fb4e5e2, tag=null, root-is-layout-requested=false, has-input-connection=false, x=624.0, y=640.0}"
```