CAT-FIX Fix NullPointerException when cloning a Look
When copying all values during the clone process, the Look may access
the LookDatas TextureRegion[1]. So the LookData has to be set before
copying all values.

[1] https://github.com/Catrobat/Catroid/blob/4de61c5d6e17c447abfbe18e5f76ac9377830e67/catroid/src/main/java/org/catrobat/catroid/content/Look.java#L154

E/BaseExceptionHandler: unhandled exception
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.badlogic.gdx.graphics.g2d.TextureRegion org.catrobat.catroid.common.LookData.getTextureRegion()' on a null object reference
        at org.catrobat.catroid.content.Look.copyLookForSprite(Look.java:154)