CAT-FIX Fix ClassCastException in UI tests
The Script ListView isn't always at index 0 and therefore has to be
searched by checking the instances of the current ListViews.

java.lang.ClassCastException: android.widget.ExpandableListConnector
cannot be cast to org.catrobat.catroid.ui.adapter.BrickAdapter